### ISSUE TITLE
cgi-bin/small.pl does not work on your testing server

### ISSUE THREAD

**Issue by nixhr** [FrankThomasTveter/astro-api#13]
Here is the URL from your wiki:
http://astro.met.no/astro/cgi-bin/small.pl?lat=40.7127&lon=-74.0059&date=2019-03-28&offset=-05:00

It returns 404.

BTW, both short.pl and state.pl work ok.

**Comment by FrankThomasTveter** [comment]
The `astro.met.no`-alias has been updated to point to the new demo-server (with small.pl installed). It may take some days for this change to propagate to all external users.
